
# html lang
language: ja

# main menu navigation
menu:
  Home: /
  About: about
  Slides: slides
#  Archives: archives

social:
  GitHub: https://github.com/y-takashina
  Twitter: https://twitter.com/takashinayuya
#  Facebook: https://www.facebook.com/yuya.takashina.3
  LinkedIn: https://www.linkedin.com/in/yuya-takashina-a18864135/

# Google analytics
google_analytics:

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/random.css
- /css/vegas.min.css
- /css/highlight-railscasts.css
- /css/jquery.fancybox.css
- /css/iconfont/iconfont.css
- /css/jquery.fancybox-thumbs.css
- /css/plyr.css

# scripts loaded in the end of the body
scripts:
- /js/jquery-2.2.3.min.js
- /js/vegas.min.js
- /js/random.js
- /js/highlight.pack.js
- /js/jquery.mousewheel.pack.js
- /js/jquery.fancybox.pack.js
- /js/jquery.fancybox-thumbs.js
- /js/plyr.js

# ignore visitor statistics on special server, for example on you local computer or debugging server
isIgnoreSpecialHostVisitor: true
ignoreHostList:
  - localhost
  - 127.0.0.1

# if you want to turn off the background images, pleaase set this value as true
turnoffBackgroundImage: 
  # home page
  index: false
  # arcihve / categories / tags
  post_list: false
  # post and page
  post: true
# when you turn off backgrounds, you can set a background color.
backgroundColor: 34495E
 
backgroundImages:
- /bg.jpg

vegasConfig:
  # more about config http://vegas.jaysalvat.com/documentation/settings/
  # animation: 'random'
  # transition: 'swirlRight'
  preload-Image: true
  transition:
    # - slideLeft2
    # - slideRight2
    # - zoomIn
    # - swirLeft
    # - swirRight
    # - flash
    # - flash2
  timer: true
  delay: 5000
  shuffle: true
  count: 28

unsplashConfig:
  # more about config on https://unsplash.it/
  # blur: true
  gravity: 'north' # north, east, south, west, center
  # greyscale: true

# do not like fancybox, set this as false, this will turn it off
fancybox: true

# set the visibility of hide button in left bottom.
hideButtonVisibility: false